name: qr_scanner
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.11.1
  cloud_firestore: ^0.11.0+2
  google_sign_in: ^4.0.1+3
  url_launcher: ^5.0.2
  firebase_core: ^0.4.0+1
  firebase_analytics: ^3.0.1
  shared_preferences: ^0.5.1+1
  intl: ^0.15.7
  provider: ^2.0.1
  sliding_up_panel: ^0.3.4
  flushbar: ^1.4.0
  qr_flutter: ^2.0.0+51
  permission_handler: ^2.2.0
  vibration: ^1.0.2
  barcode_scan:
    git:
      ref: master
      url: https://github.com/ArielMartinezViera/flutter_barcode_reader
  contacts_service:
    git:
      ref: master
      url: https://github.com/ArielMartinezViera/flutter_contacts

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: JapaneseStyle
      fonts:
      - asset: assets/fonts/japanese_style.ttf

    - family: DomoAregato
      fonts:
      - asset: assets/fonts/DomoAregato_normal.ttf

    - family: Video
      fonts:
      - asset: assets/fonts/Video.ttf

  assets:
    - assets/images/main_logo.png
    - assets/images/main_logo_white.png
    - assets/images/logo.png
    - assets/images/iron-man-silhouette.png
    - assets/images/google-logo.png
    - assets/images/google-logo-1.png
    - assets/images/google-logo-2.png

    - assets/icons/moon_icon.png
    - assets/icons/sun_icon.png
