name: qr_scanner
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  google_sign_in: ^4.3.0
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+3
  intl: ^0.16.1
  provider: ^3.2.0
  sliding_up_panel: ^1.0.0
  flushbar: 1.6.0
  qr_flutter: ^3.2.0
  permission_handler: ^4.4.0
  vibration: ^1.2.4
  barcode_scan:
    path: packages/flutter_barcode_reader
  contacts_service:
    git:
      ref: master
      url: https://github.com/ArielMartinezViera/flutter_contacts
  easy_permission_validator: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: JapaneseStyle
      fonts:
      - asset: assets/fonts/japanese_style.ttf

    - family: DomoAregato
      fonts:
      - asset: assets/fonts/DomoAregato_normal.ttf

    - family: Video
      fonts:
      - asset: assets/fonts/Video.ttf

  assets:
    - assets/images/main_logo.png
    - assets/images/main_logo_white.png
    - assets/images/logo.png
    - assets/images/iron-man-silhouette.png
    - assets/images/google-logo.png
    - assets/images/google-logo-1.png
    - assets/images/google-logo-2.png

    - assets/icons/moon_icon.png
    - assets/icons/sun_icon.png
